% Test script
clear all;
addpath("/home/pjarosik/src/arrus/build/api/matlab/wrappers");
addpath("/home/pjarosik/src/arrus/api/matlab/");

import arrus.ops.us4r.*;
import arrus.framework.*;

arrus.initialize("clogLevel", "INFO");

pulse = arrus.ops.us4r.Pulse('centerFrequency', 5e6, "nPeriods", 3.5);

seq = TxRxSequence( ...
    "ops", [ ...
      TxRx(...
        "tx", Tx("aperture", true(1, 192), 'delays', zeros(1, 192), "pulse", pulse), ...
        "rx", Rx("aperture", true(1, 192), "sampleRange", [0, 4096]), ...
        "pri", 110e-6), ...
       TxRx(...
         "tx", Tx("aperture", true(1, 192), 'delays', zeros(1, 192), "pulse", pulse), ...
         "rx", Rx("aperture", true(1, 192), "sampleRange", [0, 4096]), ...
         "pri", 110e-6)])

scheme = Scheme('txRxSequence', seq);

session = arrus.session.Session("/home/pjarosik/us4r.prototxt");
pause(1);
buffer = session.upload(scheme);
pause(1);
