% Example script for diverging wave

%% Initialize the system
addpath('..\');
addpath('..\arrus');

% Make sure the configuration in the *.prototxt file is correct.
us  = Us4R('configFile', 'us4r.prototxt', 'logTime', true);

%% Data collection
seq0 = CustomTxRxSequence(  'txApertureCenter',    0e-3, ...
                            'txApertureSize',      64, ...
                            'rxApertureCenter',    0e-3, ...
                            'rxApertureSize',      64, ...
                            'txFocus',             100e-3, ...
                            'txAngle',             (-45:1:45)*pi/180, ...
                            'speedOfSound',        1540, ...
                            'txFrequency',         2.5e6, ...
                            'txNPeriods',          2, ...
                            'txVoltage',           20, ...
                            'rxDepthRange',        200e-3, ...
                            'nRepetitions',        1, ...
                            'tgcStart',            14, ...
                            'tgcSlope',            50, ...
                            'hwDdcEnable',         false, ...
                            'decimation',          6, ...
                            'workMode',            'SYNC', ...
                            'sri',                 0, ...
                            'txPri',               500e-6, ...
                            'bufferSize',          32);

seq1 = CustomTxRxSequence(  'txApertureCenter',    0e-3, ...
                            'txApertureSize',      64, ...
                            'rxApertureCenter',    0e-3, ...
                            'rxApertureSize',      64, ...
                            'txFocus',             -10e-3, ...
                            'txAngle',             (-30:5:30)*pi/180, ...
                            'speedOfSound',        1540, ...
                            'txFrequency',         2.5e6, ...
                            'txNPeriods',          2, ...
                            'txVoltage',           20, ...
                            'rxDepthRange',        200e-3, ...
                            'nRepetitions',        1, ...
                            'tgcStart',            14, ...
                            'tgcSlope',            50, ...
                            'hwDdcEnable',         false, ...
                            'decimation',          6, ...
                            'workMode',            'SYNC', ...
                            'sri',                 0, ...
                            'txPri',               500e-6, ...
                            'bufferSize',          32);

rec0 = Reconstruction(      'gridModeEnable',      false, ...
                            'xGrid',               (-80:0.20:80)*1e-3, ...
                            'zGrid',               (  0:0.20:200)*1e-3, ...
                            'bmodeRxTangLim',      [-0.8 0.8], ...
                            'rxApod',              hamming(100).');

rec1 = Reconstruction(      'gridModeEnable',      true, ...
                            'xGrid',               (-80:0.20:80)*1e-3, ...
                            'zGrid',               (  0:0.20:200)*1e-3, ...
                            'bmodeRxTangLim',      [-0.8 0.8], ...
                            'rxApod',              hamming(100).');

us.uploadSequence([seq0, seq1]);
us.selectSequence(1, 0);
us.setReconstruction(rec0);

display0 = BModeDisplay(rec0, 'dynamicRange', [0 60]);
[rawBuff0,~,sriBuff0] = us.runLoop(@display0.isOpen, @display0.updateImg);

us.selectSequence(2, 0);
us.setReconstruction(rec0);
display1 = BModeDisplay(rec0, 'dynamicRange', [0 60]);
[rawBuff1,~,sriBuff1] = us.runLoop(@display1.isOpen, @display1.updateImg, ...
                                        'bufferType',   'raw', ...
                                        'bufferMode',   'subs', ...
                                        'bufferSize',   100);

%% Close session
us.closeSession;







