
% path to the MATLAB API files
addpath('../arrus');
addpath("C:\Users\pkarwat\Documents\GitHub\arrus\install\matlab");
addpath("C:\Users\pkarwat\Documents\GitHub\arrus\api\matlab");

%% Initialize the system, sequence, and reconstruction
us	= Us4R(     'probeName',   'SL1543', ...
                'adapterType', 'esaote3', ...
                'voltage',      10, ...
                'logTime',      true);

seq1 = CustomTxRxSequence(  'txApertureCenter', 0*1e-3, ...
                            'txApertureSize',   192, ...
                            'rxApertureCenter', 20*1e-3, ...
                            'rxApertureSize',   128, ...
                            'txFocus',          [inf]*1e-3, ...
                            'txAngle',          [-15 0 15]*pi/180, ...
                            'speedOfSound',     1490, ...
                            'txFrequency',      6e6, ...
                            'txNPeriods',       2, ...
                            'rxNSamples',       3*1024, ...
                            'tgcStart',         14, ...
                            'tgcSlope',         2e2, ...
                            'txPri',            500*1e-6);

us.upload(seq1);
rf1 = us.run;

%%
figure, imagesc(rf1(:,:)), colormap("jet"), colorbar, set(gca,'CLim',[-1 1]*1e3);

