
% path to the MATLAB API files
addpath('C:\Users\Public\us4oem-releases\ref-91\matlab');

nUs4OEM     = 2;
probeName	= 'LA/20/128';
adapterType = 'atl/philips';

txFrequency = 19.8e6;
samplingFrequency = 65e6;
fsDivider = 1;
txAmplitude = 15; % [V]
[filtB,filtA] = butter(2,[0.5 1.5]*txFrequency/(samplingFrequency/fsDivider/2),'bandpass');

% xgridmm = -6.35:0.05:6.35;
rfRangemm = [8, 12];
xgridmm = -6.35:0.05:6.35;
zgridmm  = rfRangemm(1):0.05:rfRangemm(2);

% Us4MEX(0, "AddLogFile", "us4mex_trace.log", 0);

%% Initialize the system, sequence, and reconstruction
us	= Us4R(nUs4OEM, probeName, adapterType, txAmplitude, true);

seqSTA = STASequence(	'txApertureCenter', (-10:3:10)*1e-3, ...
                        'txApertureSize',   1, ...
                        'rxApertureCenter', 0*1e-3, ...
                        'rxApertureSize',   128, ...
                        'txFocus',          -6*1e-3, ...
                        'txAngle',          0*pi/180, ...
                        'speedOfSound',     1490, ...
                        'txFrequency',      txFrequency, ...
                        'txNPeriods',       2, ...
                        'rxNSamples',       round(8*1024/fsDivider), ...
                        'nRepetitions',     1, ...
                        'txPri',            200*1e-6, ...
                        'tgcStart',         14, ...
                        'tgcSlope',         2e2, ...
                        'fsDivider',        fsDivider);                        


seqPWI = PWISequence(	'txApertureCenter', 0*1e-3, ...
                        'txApertureSize',   128, ...
                        'rxApertureCenter', 0*1e-3, ...
                        'rxApertureSize',   128, ...
                        'txFocus',          inf*1e-3, ...
                        'txAngle',          [0]*pi/180, ... %[-5,0,5]*pi/180, ...
                        'speedOfSound',     1490, ...
                        'txFrequency',      txFrequency, ...
                        'txNPeriods',       2, ...
                        'rxDepthRange',     rfRangemm*1e-3, ...                 
                        'nRepetitions',     16, ...
                        'txPri',            500*1e-6, ...
                        'tgcStart',         14, ...
                        'tgcSlope',         2e2, ...
                        'fsDivider',        fsDivider);

seqLIN = LINSequence(	'txCenterElement',	1:128, ...
                        'txApertureSize',   1, ...
                        'rxCenterElement',	1:128, ...
                        'rxApertureSize',   1, ...
                        'txFocus',          20*1e-3, ...
                        'txAngle',          0*pi/180, ...
                        'speedOfSound',     1490, ...
                        'txFrequency',      txFrequency, ...
                        'txNPeriods',       2, ...
                        'rxDepthRange',     rfRangemm*1e-3, ...
                        'nRepetitions',     1, ...
                        'txPri',            200*1e-6, ...
                        'tgcStart',         14, ...
                        'tgcSlope',         2e2, ...
                        'fsDivider',        fsDivider);                        

% GPU/CPU reconstruction implemented in matlab.
rec = Reconstruction(   'filterEnable',     true, ...
                        'filterACoeff',     filtA, ...
                        'filterBCoeff',     filtB, ...
                        'iqEnable',         true, ...
                        'cicOrder',         2, ...
                        'decimation',       1, ...
                        'xGrid',            xgridmm*1e-3, ...
                        'zGrid',            zgridmm*1e-3);
disp('uploading...')
% us.upload(seqSTA, rec);
% us.upload(seqPWI, rec);
us.upload(seqLIN, rec);
disp('uploaded')
%% Run sequence and reconstruction
[rf,img] = us.run;
% 
% display = BModeDisplay((-20:0.10:20)*1e-3, (  0:0.10:50)*1e-3);
% us.runLoop(@display.isOpen, @display.updateImg);


%%

[nrow, ncol] = size(img);
xticks = linspace(1,ncol,5);
zticks = linspace(1,nrow,5);
drange = 60; % [dB]


xtickslab = linspace(xgridmm(1),xgridmm(end),5);
ztickslab = linspace(zgridmm(1),zgridmm(end),5);
figure
    imagesc(img)
    colormap(gray)
    set(gca, 'clim', [max(img(:))-drange,max(img(:))])
    set(gca, ...
        'xticklabel',xtickslab, ...
        'yticklabel',ztickslab, ...
        'xtick',xticks,...
        'ytick',zticks ...        
        )
    xlabel('[mm]')
    ylabel('[mm]')
    daspect([1,1,1])
%     ylabel('samples')
%     xlabel('arbitrary image lines')

