
addpath('../arrus');

nArius      = 2;
probeName	= 'AL2442';

txFrequency = 7e6;
samplingFrequency = 65e6;

[filtB,filtA] = butter(2,[0.5 1.5]*txFrequency/(samplingFrequency/2),'bandpass');

%% Initialize the system, sequence, and reconstruction
us	= Us4R(nArius,probeName);

seq = PWISequence(      'txCenterElement',  [], ...
                        'txApertureCenter', zeros(1,3), ...
                        'txApertureSize',   192, ...
                        'txFocus',          inf(1,3), ...
                        'txAngle',          [-10 0 10]*pi/180, ...
                        'speedOfSound',     1450, ...
                        'txFrequency',      txFrequency, ...
                        'txNPeriods',       2, ...
                        'rxNSamples',       8*1024, ...
                        'txPri',            200);

rec = Reconstruction(   'filterEnable',     true, ...
                        'filterACoeff',     filtA, ...
                        'filterBCoeff',     filtB, ...
                        'filterDelay',      0, ...
                        'iqEnable',         true, ...
                        'cicOrder',         2, ...
                        'decimation',       4, ...
                        'xGrid',            (-20:0.10:20)*1e-3, ...
                        'zGrid',            (  0:0.10:50)*1e-3);

us.upload(seq,rec);

%% Run sequence and reconstruction
[rf,img] = us.run;



