
% path to the MATLAB API files
addpath('../arrus');

txFrequency = 5e6;
samplingFrequency = 65e6;
fsDivider = 1;

[filtB,filtA] = butter(2,[0.5 1.5]*txFrequency/(samplingFrequency/fsDivider/2),'bandpass');

nUs4OEM = 2;
%% Initialize the system, sequence, and reconstruction
us	= Us4R('nUs4OEM',      nUs4OEM, ...
           'probeName',   'AC2541', ...
           'adapterType', 'esaote3', ...
           'voltage',      30, ...
           'logTime',      true);
       
% Us4MEX(0, "AddLogFile", "trace.log", 0);

seqSTA = STASequence(	'txApertureCenter', (-15:3:15)*1e-3, ...
                        'txApertureSize',   32, ...
                        'rxApertureCenter', 0*1e-3, ...
                        'rxApertureSize',   192, ...
                        'txFocus',          -6*1e-3, ...
                        'txAngle',          0*pi/180, ...
                        'speedOfSound',     1450, ...
                        'txFrequency',      txFrequency, ...
                        'txNPeriods',       2, ...
                        'rxNSamples',       round(8*1024/fsDivider), ...
                        'nRepetitions',     1, ...
                        'txPri',            200*1e-6, ...
                        'tgcStart',         14, ...
                        'tgcSlope',         2e2, ...
                        'fsDivider',        fsDivider);                        


seqPWI = PWISequence(	'txApertureCenter', 0*1e-3, ...
                        'txApertureSize',   192, ...
                        'rxApertureCenter', 0*1e-3, ...
                        'rxApertureSize',   192, ...
                        'txFocus',          inf*1e-3, ...
                        'txAngle',          [-5,0,5]*pi/180, ...
                        'speedOfSound',     1490, ...
                        'txFrequency',      txFrequency, ...
                        'txNPeriods',       2, ...
                        'rxDepthRange',     [0e-3,40e-3], ...                 
                        'nRepetitions',     1, ...
                        'txPri',            200*1e-6, ...
                        'tgcStart',         14, ...
                        'tgcSlope',         2e2, ...
                        'fsDivider',        fsDivider);

seqLIN = LINSequence(	'txCenterElement',	8:184, ...
                        'txApertureSize',   64, ...
                        'rxCenterElement',	8:184, ...
                        'rxApertureSize',   64, ...
                        'txFocus',          30*1e-3, ...
                        'txAngle',          0*pi/180, ...
                        'speedOfSound',     1490, ...
                        'txFrequency',      txFrequency, ...
                        'txNPeriods',       3, ...
                        'rxNSamples',       round(4*1024/fsDivider), ...
                        'nRepetitions',     1, ...
                        'txPri',            200*1e-6, ...
                        'tgcStart',         14, ...
                        'tgcSlope',         2e2, ...
                        'txInvert',         0, ...
                        'fsDivider',        fsDivider);                        

% GPU/CPU reconstruction implemented in matlab.
rec = Reconstruction(   'filterEnable',     true, ...
                        'filterACoeff',     filtA, ...
                        'filterBCoeff',     filtB, ...
                        'iqEnable',         true, ...
                        'cicOrder',         2, ...
                        'decimation',       1, ...
                        'xGrid',            (-40:0.10:40)*1e-3, ...
                        'zGrid',            (  0:0.10:70)*1e-3);

% us.upload(seqSTA, rec);
% us.upload(seqPWI, rec);
us.upload(seqLIN, rec);

%% Run sequence and reconstruction
% [rf,img] = us.run;
% 
display = BModeDisplay((-40:0.10:40)*1e-3, (  0:0.10:70)*1e-3);
us.runLoop(@display.isOpen, @display.updateImg);
