
%% paths to the MATLAB API/ARRUS files
pathArrus = 'C:\Users\user\Documents\GitHub\arrus\'; % path to the arrus repo

addpath([pathArrus 'install\matlab']);
addpath([pathArrus 'api\matlab']);
addpath([pathArrus 'api\matlab\arrus']);

%% Initialize the system
us = Us4R(  'configFile',   'us4r.prototxt', ...
            'voltage',      20);

seq = CustomTxRxSequence(   'txApertureCenter', 0*1e-3, ...
                            'txApertureSize',   us.getNProbeElem, ...
                            'rxApertureCenter', 0*1e-3, ...
                            'rxApertureSize',   us.getNProbeElem, ...
                            'txFocus',          inf*1e-3, ...
                            'txAngle',          (-15:3:15)*pi/180, ...
                            'speedOfSound',     1490, ...
                            'txFrequency',      6e6, ...
                            'txNPeriods',       2, ...
                            'rxNSamples',       4*1024, ...
                            'hwDdcEnable',      false);

us.upload(seq);

%% Run sequence
% Single execution of the sequence, collecting rf data
rf = us.run;

%% Close session
us.closeSession;


