#ifndef ARRUS_ARRUS_CORE_API_FRAMEWORK_FIFOBLOCKINGBUFFER_H
#define ARRUS_ARRUS_CORE_API_FRAMEWORK_FIFOBLOCKINGBUFFER_H

namespace arrus::framework {

}

#endif //ARRUS_ARRUS_CORE_API_FRAMEWORK_FIFOBLOCKINGBUFFER_H
