#     ██████████      ███████                     
#    ▒▒███▒▒▒▒███   ███▒▒▒▒▒███                   
#     ▒███   ▒▒███ ███     ▒▒███                  
#     ▒███    ▒███▒███      ▒███                  
#     ▒███    ▒███▒███      ▒███                  
#     ▒███    ███ ▒▒███     ███                   
#     ██████████   ▒▒▒███████▒                    
#    ▒▒▒▒▒▒▒▒▒▒      ▒▒▒▒▒▒▒                      
#                                                                                
#                                                 
#     ██████   █████    ███████    ███████████    
#    ▒▒██████ ▒▒███   ███▒▒▒▒▒███ ▒█▒▒▒███▒▒▒█    
#     ▒███▒███ ▒███  ███     ▒▒███▒   ▒███  ▒     
#     ▒███▒▒███▒███ ▒███      ▒███    ▒███        
#     ▒███ ▒▒██████ ▒███      ▒███    ▒███        
#     ▒███  ▒▒█████ ▒▒███     ███     ▒███        
#     █████  ▒▒█████ ▒▒▒███████▒      █████       
#    ▒▒▒▒▒    ▒▒▒▒▒    ▒▒▒▒▒▒▒       ▒▒▒▒▒        
#                                                 
#                                                 
#      █████████  █████   █████ █████ ███████████ 
#     ███▒▒▒▒▒███▒▒███   ▒▒███ ▒▒███ ▒▒███▒▒▒▒▒███
#    ▒███    ▒▒▒  ▒███    ▒███  ▒███  ▒███    ▒███
#    ▒▒█████████  ▒███████████  ▒███  ▒██████████ 
#     ▒▒▒▒▒▒▒▒███ ▒███▒▒▒▒▒███  ▒███  ▒███▒▒▒▒▒▒  
#     ███    ▒███ ▒███    ▒███  ▒███  ▒███        
#    ▒▒█████████  █████   █████ █████ █████       
#     ▒▒▒▒▒▒▒▒▒  ▒▒▒▒▒   ▒▒▒▒▒ ▒▒▒▒▒ ▒▒▒▒▒        
#
# Reason: development branch of docker-base

services:
  arrus-build:
    build: https://github.com/us4useu/docker-base.git#clang-dev:.
    image: arrus-build
    volumes:
      - ./:/usr/src/arrus
      - ../us4r-api:/usr/src/us4r-api
      - ~/.us4r-docker/.conan2:/root/.conan2
    working_dir: /usr/src/arrus
    tty: true
    stdin_open: true
    entrypoint: [ "/bin/bash", "--rcfile", "/root/devenv_setup.sh" ]
