#ifndef ARRUS_CORE_API_DEVICES_ADAPTER_ADAPTERSETTINGS_H
#define ARRUS_CORE_API_DEVICES_ADAPTER_ADAPTERSETTINGS_H

namespace arrus {
class ProbeAdapterSettings {
private:

};
}

#endif //ARRUS_CORE_API_DEVICES_ADAPTER_ADAPTERSETTINGS_H
