# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _hv256
else:
    import _hv256

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class II2CMaster(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Write(self, address, data, length):
        return _hv256.II2CMaster_Write(self, address, data, length)

    def Read(self, address, data, length):
        return _hv256.II2CMaster_Read(self, address, data, length)

    def WriteAndRead(self, address, writedata, writelength, readdata, readlength):
        return _hv256.II2CMaster_WriteAndRead(self, address, writedata, writelength, readdata, readlength)
    __swig_destroy__ = _hv256.delete_II2CMaster

# Register II2CMaster in _hv256:
_hv256.II2CMaster_swigregister(II2CMaster)

class HV256(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, i2cMaster):
        _hv256.HV256_swiginit(self, _hv256.new_HV256(i2cMaster))
    __swig_destroy__ = _hv256.delete_HV256

    def SetHVVoltage(self, voltage):
        return _hv256.HV256_SetHVVoltage(self, voltage)

    def SetDefaultHVPVoltage(self, voltage):
        return _hv256.HV256_SetDefaultHVPVoltage(self, voltage)

    def SetDefaultHVMVoltage(self, voltage):
        return _hv256.HV256_SetDefaultHVMVoltage(self, voltage)

    def EnableHV(self):
        return _hv256.HV256_EnableHV(self)

    def DisableHV(self):
        return _hv256.HV256_DisableHV(self)

# Register HV256 in _hv256:
_hv256.HV256_swigregister(HV256)



