#ifndef ARRUS_CORE_COMMON_LOGGING_LOGGERFACTORY_H
#define ARRUS_CORE_COMMON_LOGGING_LOGGERFACTORY_H

namespace arus {

class LoggerFactory {

};

}

#endif //ARRUS_CORE_COMMON_LOGGING_LOGGERFACTORY_H
