#ifndef ARRUS_CORE_API_DEVICES_US4R_HVPSFUSESETTINGS_H
#define ARRUS_CORE_API_DEVICES_US4R_HVPSFUSESETTINGS_H

#include <optional>

#include "std4us/Optional.hpp"
#include "std4us/StdInterop.hpp"

namespace arrus::devices {

class HVPSFuseSettingsBuilder;

/**
 * OEM+ HVPS fuse settings.
 *
 * This class allows to specify the maximum allowable power/current on levels 1 and 2 (HV rail 1 and 0).
 * All the thresholds are state-safe, i.e., If the current or power exceeds the selected maximum thresholds, the
 * HVPS will be switched off and the system will stop executing TX/RX sequence.
 *
 * NOTE: all the thresholds are optional; in particular, you can specify the new thresholds for only the selected
 * levels/measurements.
 *
 * Please use arrus::devices::HVPSFuseSettingsBuilder to create a new instance of this class.
 *
 * Member storage uses std4us::Optional for ABI stability. The std::optional
 * accessors are inline header-only backward-compatibility shims.
 *
 * @param level1MaxCurrentThreshold: max allowable current generated by a single OEM during the run-time, amplitude level 1 [A]
 * @param level1MaxPowerThreshold: max allowable power generated by a single OEM during the run-time, amplitude level 1 [W]
 * @param level2MaxCurrentThreshold: max allowable current generated by a single OEM during the run-time, amplitude level 2 [A]
 * @param level2MaxPowerThreshold: max allowable power generated by a single OEM during the run-time, amplitude level 2 [W]
 */
class HVPSFuseSettings {
public:

    [[nodiscard]] std::optional<float> getLevel1MaxCurrentThreshold() const { return std4us::toStd(level1MaxCurrentThreshold); }
    [[nodiscard]] std::optional<float> getLevel1MaxPowerThreshold() const { return std4us::toStd(level1MaxPowerThreshold); }
    [[nodiscard]] std::optional<float> getLevel2MaxCurrentThreshold() const { return std4us::toStd(level2MaxCurrentThreshold); }
    [[nodiscard]] std::optional<float> getLevel2MaxPowerThreshold() const { return std4us::toStd(level2MaxPowerThreshold); }
    [[nodiscard]] std::optional<float> getLevel1StaticVoltageMargin() const { return std4us::toStd(level1StaticVoltageMargin); }
    [[nodiscard]] std::optional<float> getLevel2StaticVoltageMargin() const { return std4us::toStd(level2StaticVoltageMargin); }

    [[nodiscard]] const std4us::Optional<float> &getLevel1MaxCurrentThresholdNative() const { return level1MaxCurrentThreshold; }
    [[nodiscard]] const std4us::Optional<float> &getLevel1MaxPowerThresholdNative() const { return level1MaxPowerThreshold; }
    [[nodiscard]] const std4us::Optional<float> &getLevel2MaxCurrentThresholdNative() const { return level2MaxCurrentThreshold; }
    [[nodiscard]] const std4us::Optional<float> &getLevel2MaxPowerThresholdNative() const { return level2MaxPowerThreshold; }
    [[nodiscard]] const std4us::Optional<float> &getLevel1StaticVoltageMarginNative() const { return level1StaticVoltageMargin; }
    [[nodiscard]] const std4us::Optional<float> &getLevel2StaticVoltageMarginNative() const { return level2StaticVoltageMargin; }

private:
    friend class HVPSFuseSettingsBuilder;

    HVPSFuseSettings() = default;

    std4us::Optional<float> level1MaxCurrentThreshold;
    std4us::Optional<float> level1MaxPowerThreshold;
    std4us::Optional<float> level1StaticVoltageMargin;
    std4us::Optional<float> level2MaxCurrentThreshold;
    std4us::Optional<float> level2MaxPowerThreshold;
    std4us::Optional<float> level2StaticVoltageMargin;
};

/**
 * HVPS Fuse settings builder.
 *
 * Example usage:
 *
 * ::
 *  HVPSFuseSettingsBuilder builder;
 *  const HVPSFuseSettings settings = builder.setLevel1MaxCurrentThreshold(20)
 *                                           .setLevel2MaxPowerThreshold(1)
 *                                           .build();
 */
class HVPSFuseSettingsBuilder {
public:
    HVPSFuseSettingsBuilder() = default;

    HVPSFuseSettingsBuilder& setLevel1MaxCurrentThreshold(const float value) {
        settings.level1MaxCurrentThreshold = value;
        return *this;
    }

    HVPSFuseSettingsBuilder& setLevel1MaxPowerThreshold(const float value) {
        settings.level1MaxPowerThreshold = value;
        return *this;
    }

    HVPSFuseSettingsBuilder& setLevel1StaticVoltageMargin(const float value) {
        settings.level1StaticVoltageMargin = value;
        return *this;
    }

    HVPSFuseSettingsBuilder& setLevel2MaxCurrentThreshold(const float value) {
        settings.level2MaxCurrentThreshold = value;
        return *this;
    }

    HVPSFuseSettingsBuilder& setLevel2MaxPowerThreshold(const float value) {
        settings.level2MaxPowerThreshold = value;
        return *this;
    }

    HVPSFuseSettingsBuilder& setLevel2StaticVoltageMargin(const float value) {
        settings.level2StaticVoltageMargin = value;
        return *this;
    }

    [[nodiscard]] HVPSFuseSettings build() {
        auto result = settings;
        settings = HVPSFuseSettings();
        return result;
    }

private:

    HVPSFuseSettings settings;
};


}// namespace arrus::devices

#endif//ARRUS_CORE_API_DEVICES_US4R_HVPSFUSESETTINGS_H
