#ifndef ARRUS_CORE_API_DEVICES_US4R_US4RBACKENDSETTINGS_H
#define ARRUS_CORE_API_DEVICES_US4R_US4RBACKENDSETTINGS_H

namespace arrus::devices {

}

#endif//ARRUS_CORE_API_DEVICES_US4R_US4RBACKENDSETTINGS_H
